module.exports = {
  "Source Pocket": {
    "💻 Contribute": ["style-guide"],
    "📚 Programming Languages Pocket": [
      "assembly",
      "c",
      "cplusplus",
      "csharp",
      "dart",
      "go",
      "java",
      "kotlin",
      "lua",
      "matlab",
      "python",
      "r",
      "ruby",
      "rust",
      "swift",
    ],
    "🌐 Web Development Pocket": [
      "hosting-and-servers",
      "asp-net-mvc",
      "asp-net-webforms",
      "wordpress",
      "angularjs",
      "css",
      "django",
      "flask",
      "html",
      "jquery",
      "java-spring",
      "javascript",
      "laravel",
      "nodejs",
      "netcore",
      "php",
      "reactjs",
      "ruby-on-rails",
      "typescript",
      "vuejs",
    ],
    "🛠 Development Tools Pocket": [
      "azure",
      "aws",
      "android-studio",
      "docker",
      "git",
      "visualstudio",
      "visual-studio-code",
    ],
    "🤔 Operating Systems Pocket": ["macos", "windows", "gnu-linux"],
    "😥 Not Categorized Yet": ["front-end", "design"],
  },
};
