module.exports = {
  "Source Pocket": {
    "💻 Contribute": ["style-guide"],
    "📚 Programming Languages Pocket": [
      "programming-languages/assembly",
      "programming-languages/c",
      "programming-languages/cplusplus",
      "programming-languages/csharp",
      "programming-languages/dart",
      "programming-languages/go",
      "programming-languages/java",
      "programming-languages/kotlin",
      "programming-languages/lua",
      "programming-languages/matlab",
      "programming-languages/python",
      "programming-languages/r",
      "programming-languages/ruby",
      "programming-languages/rust",
      "programming-languages/swift",
    ],
    "🌐 Web Development Pocket": [
      "web-development/hosting-and-servers",
      "web-development/asp-net-mvc",
      "web-development/asp-net-webforms",
      "web-development/wordpress",
      "web-development/angularjs",
      "web-development/css",
      "web-development/django",
      "web-development/flask",
      "web-development/html",
      "web-development/jquery",
      "web-development/java-spring",
      "web-development/javascript",
      "web-development/laravel",
      "web-development/nodejs",
      "web-development/netcore",
      "web-development/php",
      "web-development/reactjs",
      "web-development/ruby-on-rails",
      "web-development/typescript",
      "web-development/vuejs",
    ],
    "🛠 Development Tools Pocket": [
      "development-tools/azure",
      "development-tools/aws",
      "development-tools/android-studio",
      "development-tools/docker",
      "development-tools/git",
      "development-tools/visualstudio",
      "development-tools/visual-studio-code",
    ],
    "🤔 Operating Systems Pocket": [
      "operating-systems/macos",
      "operating-systems/windows",
      "operating-systems/gnu-linux",
    ],
    "🛠 Mobile Development Pocket": [
      "mobile-development/android",
      "mobile-development/flutter",
      "mobile-development/ios",
      "mobile-development/reactnative",
      "mobile-development/xamarin",
    ],
    "🎨 Graphic Design Pocket": [
      "graphic-design/general-design",
      "graphic-design/ui-ux-design",
      "graphic-design/illustrations",
      "graphic-design/motion-design",
      "graphic-design/sound-design",
      "graphic-design/misc-design",
      "graphic-design/photo-and-video",
      "graphic-design/other",
    ],
    "⚡️ Embedded Systems Pocket": [
      "embedded-systems/arm",
      "embedded-systems/arduino",
      "embedded-systems/raspberry-pi",
      "embedded-systems/other",
    ],
    "😥 Not Categorized Yet": ["front-end", "design"],
  },
};
